#pragma once

namespace engine::core::runtime::input {
    enum InputDeviceType {
        INPUT_DEVICE_TYPE_UNKNOWN,
        INPUT_DEVICE_TYPE_MOUSE,
        INPUT_DEVICE_TYPE_KEYBOARD,
        INPUT_DEVICE_TYPE_GAMEPAD,
        INPUT_DEVICE_TYPE_TOUCH
    };

    enum InputDeviceButton {
        INPUT_DEVICE_BUTTON_UNKNOWN,

        // Mouse Buttons
        INPUT_DEVICE_BUTTON_MOUSE_LEFT,
        INPUT_DEVICE_BUTTON_MOUSE_RIGHT,
        INPUT_DEVICE_BUTTON_MOUSE_MIDDLE,

        // Gamepad Buttons (Common buttons for gamepads)
        INPUT_DEVICE_BUTTON_GAMEPAD_A,
        INPUT_DEVICE_BUTTON_GAMEPAD_B,
        INPUT_DEVICE_BUTTON_GAMEPAD_X,
        INPUT_DEVICE_BUTTON_GAMEPAD_Y,
        INPUT_DEVICE_BUTTON_GAMEPAD_DPAD_UP,
        INPUT_DEVICE_BUTTON_GAMEPAD_DPAD_DOWN,
        INPUT_DEVICE_BUTTON_GAMEPAD_DPAD_LEFT,
        INPUT_DEVICE_BUTTON_GAMEPAD_DPAD_RIGHT,
        INPUT_DEVICE_BUTTON_GAMEPAD_LB,  // Left bumper
        INPUT_DEVICE_BUTTON_GAMEPAD_RB,  // Right bumper
        INPUT_DEVICE_BUTTON_GAMEPAD_START,
        INPUT_DEVICE_BUTTON_GAMEPAD_BACK,
        INPUT_DEVICE_BUTTON_GAMEPAD_LS,  // Left stick press
        INPUT_DEVICE_BUTTON_GAMEPAD_RS,  // Right stick press
        INPUT_DEVICE_BUTTON_GAMEPAD_PLUS,  // Switch Plus
        INPUT_DEVICE_BUTTON_GAMEPAD_MINUS, // Switch Minus
    };
    
    enum InputDeviceKey {
        INPUT_DEVICE_KEY_A,
        INPUT_DEVICE_KEY_B,
        INPUT_DEVICE_KEY_C,
        INPUT_DEVICE_KEY_ENTER,
        INPUT_DEVICE_KEY_SPACE,
    };

    enum class InputEventType {
        INPUT_EVENT_TYPE_UNKNOWN,

        // Keyboard Events
        INPUT_EVENT_TYPE_KEY_UP,
        INPUT_EVENT_TYPE_KEY_DOWN,

        // Mouse Events
        INPUT_EVENT_TYPE_MOUSE_KEY_UP,
        INPUT_EVENT_TYPE_MOUSE_KEY_DOWN,
        INPUT_EVENT_TYPE_MOUSE_MOVE,

        // Touch Events
        INPUT_EVENT_TYPE_TOUCH_START,
        INPUT_EVENT_TYPE_TOUCH_HOVER,
        INPUT_EVENT_TYPE_TOUCH_DRAG,
        INPUT_EVENT_TYPE_TOUCH_END,

        // Gamepad Events
        INPUT_EVENT_TYPE_GAMEPAD_BUTTON_UP,
        INPUT_EVENT_TYPE_GAMEPAD_BUTTON_DOWN,
        INPUT_EVENT_TYPE_GAMEPAD_AXIS_UPDATE
    };

    enum InputDeviceAxis {
        INPUT_DEVICE_AXIS_UNKNOWN,

        INPUT_DEVICE_AXIS_MOUSE,

        INPUT_DEVICE_AXIS_GAMEPAD_STICK_LEFT,
        INPUT_DEVICE_AXIS_GAMEPAD_STICK_RIGHT,
        INPUT_DEVICE_AXIS_GAMEPAD_TRIGGER_LEFT,
        INPUT_DEVICE_AXIS_GAMEPAD_TRIGGER_RIGHT,
    };
}
